### ISSUE TITLE
 TypeError: unhashable type: 'weakproxy'

### ISSUE THREAD

**Issue by dnajd** [davesnowdon/nao-recorder#61]
When I click motors on/off I get an error of:
 TypeError: unhashable type: 'weakproxy'

h1. My environment
- Kivy v1.7.2
- Python 2.7.3
- Ubuntu 12

h1. Stacktrace
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "src/main/python/recorder/main.py", line 475, in <module>
     NaoRecorderApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 600, in run
     runTouchApp()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 454, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 325, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 231, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 297, in idle
     self.dispatch_input()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 284, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 209, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 630, in on_motion
     self.dispatch('on_touch_down', me)
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 642, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 266, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 266, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/button.py", line 124, in on_touch_down
     self.dispatch('on_press')
   File "_event.pyx", line 281, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4136)
   File "src/main/python/recorder/main.py", line 419, in _on_motors
     self.robot.motors_on()
   File "/home/dnajd/development/personal/nao-recorder/src/main/python/recorder/core.py", line 299, in motors_on
     self.notify_stiffness_changed()
   File "/home/dnajd/development/personal/nao-recorder/src/main/python/recorder/core.py", line 430, in notify_stiffness_changed
     self.on_stiffness(self.get_stiff_chains())
   File "src/main/python/recorder/main.py", line 466, in _on_chain_stiffness_from_robot
     self.joints_ui.set_chain_stiffness(stiff_chains)
   File "src/main/python/recorder/main.py", line 162, in set_chain_stiffness
     stiff_chains = { name_to_chain[name] for name in stiff_chain_names if name != 'Body' }
   File "src/main/python/recorder/main.py", line 162, in <setcomp>
     stiff_chains = { name_to_chain[name] for name in stiff_chain_names if name != 'Body' }
 TypeError: unhashable type: 'weakproxy'
[INFO ] Stopping naoutil_memory__SubscriberModule
[INFO ] Stopping ALNetwork

**Comment by davesnowdon** [comment]
Fixed
