### ISSUE TITLE
Another TypeError: unhashable type: 'weakproxy' like #61

### ISSUE THREAD

**Issue by dnajd** [davesnowdon/nao-recorder#62]
This is the same as the issue #61, except happening in a different location in the code.

[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "src/main/python/recorder/main.py", line 475, in <module>
     NaoRecorderApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 600, in run
     runTouchApp()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 454, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 325, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 231, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 297, in idle
     self.dispatch_input()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 284, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 209, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 630, in on_motion
     self.dispatch('on_touch_down', me)
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 642, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 266, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 266, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 266, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/relativelayout.py", line 61, in on_touch_down
     ret = super(RelativeLayout, self).on_touch_down(touch)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/widget.py", line 266, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "_event.pyx", line 285, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4186)
   File "/usr/lib/python2.7/dist-packages/kivy/uix/button.py", line 124, in on_touch_down
     self.dispatch('on_press')
   File "_event.pyx", line 281, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4136)
   File "src/main/python/recorder/naorecorder.kv", line 1, in <module>
     #:kivy 1.0
   File "src/main/python/recorder/main.py", line 170, in toggle_chain_stiffness
     self.notify_stiffness_changed()
   File "src/main/python/recorder/main.py", line 217, in notify_stiffness_changed
     self.on_chain_stiffness(self.get_stiff_chains())
   File "src/main/python/recorder/main.py", line 210, in get_stiff_chains
     if self.is_stiff(child):
   File "src/main/python/recorder/main.py", line 193, in is_stiff
     is_joint_chain(self.child_stiffness_chain_name(child)) and \
   File "src/main/python/recorder/main.py", line 182, in child_stiffness_chain_name
     return { self.f_head_stiffness : 'Head',
 TypeError: unhashable type: 'weakproxy'
[INFO ] Stopping naoutil_memory__SubscriberModule
[INFO ] Stopping ALNetwork

**Comment by davesnowdon** [comment]
Fixed
